### ISSUE TITLE
how to convert csv to geojson

### ISSUE THREAD

**Issue by andrewzigerelli** [CodeForPittsburgh/fishfrymap#22]
Hi,  I want to update my location (Economy VFD). I know I can update the geojson directly, but I figured there is probably a script to convert the csv to geojson. The geojson is just one line..

**Comment by andrewzigerelli** [comment]
Also, how fancy can I get in the csv? We have a few road closures, and I'd like to link to maps for alternate directions. I could just do a link I suppose, but if I could embed a tiny map, that would be cool.

**Comment by gassc** [comment]
Hi @andrewzigerelli

Best way to submit an update request at the moment is to Hollen's [fish fry facebook page](https://www.facebook.com/PittsburghLentenFishFryMap); second best way is here. Eventually we'll roll out a public-facing submission/editing form, but we're just not there yet. 

The `geojson` and `csv` in [the data folder of the repo](https://github.com/CodeForPittsburgh/fishfrymap/tree/master/data) actually just a derived product / backup. The real thing (used by the map) lives in a database (AWS DynamoDB) and is accessed through an [http request](https://fishfry.codeforpgh.com/api/fishfries) and managed through a separate site. Admittedly, I need to document this all better.

For directions: right now we're linking out to Google Maps for driving directions. If there are specific road closures that aren't otherwise captured there, we can include it in the notes (based on info you submit); if you have that info on your website then folks can also see it there via our form.
